version: 2.1
orbs: 
  sixrs-gke: "sixriversystems/sixrs-gke@2"
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Set Up CI Environment
          command: |
            mkdir ci_scripts
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw"  https://api.github.com/repos/6RiverSystems/ci_scripts/contents/ci_tool.sh >> ci_scripts/ci_tool.sh
            chmod +x ci_scripts/ci_tool.sh
      - run:
          name: Install Packages
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Upgrade Database
          command: pipenv run flask db upgrade
      - run:
          name: Run Tests
          command: |
            pipenv run coverage run --source app/ tests.py
            pipenv run coverage xml
      - run:
          name: Docker Build
          command: |
            ci_scripts/ci_tool.sh --docker_build
      - persist_to_workspace:
          root: ./
          paths:
            - .
            - ci_scripts
            - .version
  publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          name: Run Release
          command: |
            ci_scripts/ci_tool.sh --run_release
      - run:
          name: Publish Docker
          command: |
            ci_scripts/ci_tool.sh --docker_publish
      - persist_to_workspace:
          root: ./
          paths:
            - .
  
workflows:
  version: 2.1

  test_and_publish:
    jobs:
      - build:
          context: 6rs-circle
      - publish:
          context: 6rs-circle
          requires:
            - build
