"""empty message

Revision ID: 7b761d7ca453
Revises: 
Create Date: 2019-01-14 23:24:55.411994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b761d7ca453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mask_map',
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('token_id', sa.String(length=128), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('external_value', sa.String(length=2048), nullable=True),
    sa.Column('exception', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['profile.token_id'], ),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_index(op.f('ix_mask_map_value'), 'mask_map', ['value'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('token_id', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=128), nullable=True),
    sa.Column('message_format', sa.String(length=128), nullable=True),
    sa.Column('incoming_endpoint', sa.String(length=2048), nullable=True),
    sa.Column('unmasked_data', sa.String(length=16777216), nullable=True),
    sa.Column('masked_data', sa.String(length=16777216), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['profile.token_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=True)
    op.create_table('message_transmission',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_transmission_id'), 'message_transmission', ['id'], unique=True)
    op.create_table('profile',
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('data', sa.String(length=16777216), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_profile_token_id'), 'profile', ['token_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('data', sa.String(length=16777216), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('active_profile', sa.String(length=128), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('last_feed_load_time', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_profile'], ['profile.token_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_profile_token_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_message_transmission_id'), table_name='message_transmission')
    op.drop_table('message_transmission')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_mask_map_value'), table_name='mask_map')
    op.drop_table('mask_map')
    # ### end Alembic commands ###
