"""add exception to mask map

Revision ID: d246b65716db
Revises: de056222fc5d
Create Date: 2019-01-14 22:06:09.623250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd246b65716db'
down_revision = 'de056222fc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mask_map', sa.Column('exception', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mask_map', 'exception')
    # ### end Alembic commands ###
