"""feed loading

Revision ID: de056222fc5d
Revises: dfd29b993e0b
Create Date: 2019-01-11 03:47:41.838283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de056222fc5d'
down_revision = 'dfd29b993e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_feed_load_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_feed_load_time')
    # ### end Alembic commands ###
